"""Reconciles team names between football-data.org (the live API, used for
the Fixtures page — official long names like "Manchester United FC") and the
training data's naming convention (football-data.co.uk/footballcsv, short
common names like "Man United").

Every entry below was verified by hand against team_stats.json — NOT
generated by fuzzy/similarity matching. That was tried first and rejected:
character-similarity matching produced dangerous false positives like
"Rayo Vallecano de Madrid" -> "Real Madrid" and "RCD Espanyol de Barcelona"
-> "Barcelona" (fierce rivals, not the same club) — a club's full name often
embeds the city name, which collides with another real club's short name.
Wrong-team predictions that *look* plausible are worse than an honest
"unknown team" fallback, so resolution here is exact-or-nothing.

Keys are accent-stripped, lowercased source names (either football-data.org's
`name` or `shortName` field) -> the canonical team_stats.json key.
"""

import unicodedata


def strip_accents(text: str) -> str:
    if not text:
        return ""
    return unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")


# Verified against team_stats.json for PL, PD, BL1, SA, FL1, DED, PPL, ELC —
# the leagues actually offered on the Fixtures page. Extend as new mismatches
# turn up; never add an entry without checking it against team_stats.json.
TEAM_NAME_ALIASES = {
    # Bundesliga
    "fc bayern munchen": "Bayern Munich", "bayern": "Bayern Munich",
    "sc paderborn 07": "Paderborn", "sc paderborn": "Paderborn",
    "eintracht frankfurt": "Ein Frankfurt", "frankfurt": "Ein Frankfurt",
    "1. fc koln": "FC Koln",
    "hamburger sv": "Hamburg", "hsv": "Hamburg",
    "sv werder bremen": "Werder Bremen", "bremen": "Werder Bremen",
    "fc schalke 04": "Schalke 04", "schalke": "Schalke 04",
    # Eredivisie
    "psv": "PSV Eindhoven",
    "fortuna sittard": "For Sittard", "sittard": "For Sittard",
    "az": "AZ Alkmaar",
    # Ligue 1
    "racing club de lens": "Lens", "rc lens": "Lens",
    "paris saint-germain fc": "Paris SG", "psg": "Paris SG",
    "stade rennais fc 1901": "Rennes", "stade rennais": "Rennes",
    "angers sco": "Angers",
    "olympique lyonnais": "Lyon", "olympique lyon": "Lyon",
    # La Liga
    "deportivo alaves": "Alaves", "alaves": "Alaves",
    "sevilla fc": "Sevilla",
    "rayo vallecano de madrid": "Vallecano", "rayo vallecano": "Vallecano",
    "rcd espanyol de barcelona": "Espanol", "espanyol": "Espanol",
    "rc deportivo la coruna": "La Coruna", "deportivo": "La Coruna",
    "club atletico de madrid": "Ath Madrid", "atleti": "Ath Madrid",
    "malaga cf": "Malaga", "malaga": "Malaga",
    "real betis balompie": "Betis", "real betis": "Betis",
    "real sociedad de futbol": "Sociedad", "real sociedad": "Sociedad",
    "athletic club": "Ath Bilbao", "athletic": "Ath Bilbao",
    "fc barcelona": "Barcelona", "barca": "Barcelona",
    # Premier League — most already resolve via shortName exact match (e.g.
    # "Manchester United FC" -> shortName "Man United" hits team_stats
    # directly), these cover the long `name` form for direct/bookmarked URLs.
    "manchester united fc": "Man United", "manchester united": "Man United",
    "manchester city fc": "Man City", "manchester city": "Man City",
    "tottenham hotspur fc": "Tottenham", "tottenham hotspur": "Tottenham",
    "newcastle united fc": "Newcastle", "newcastle united": "Newcastle",
    "west ham united fc": "West Ham", "west ham united": "West Ham",
    "wolverhampton wanderers fc": "Wolves", "wolverhampton wanderers": "Wolves",
    "coventry city fc": "Coventry", "coventry city": "Coventry",
    "hull city afc": "Hull", "hull city": "Hull",
    "ipswich town fc": "Ipswich", "ipswich town": "Ipswich",
    "nottingham forest fc": "Nott'm Forest", "nottingham": "Nott'm Forest",
    "leeds united fc": "Leeds", "leeds united": "Leeds",
    "brighton & hove albion fc": "Brighton", "brighton hove": "Brighton",
    # Serie A
    "como 1907": "Como",
    "venezia fc": "Venezia",
    # Champions League (club names differ from the domestic-league fixture
    # feed's name/shortName for these four; audited against the CL team
    # roster via /competitions/CL/teams, not a fixture-window snapshot).
    # Note: strip_accents drops non-decomposing letters like o-with-stroke
    # (o/o) rather than transliterating them, so "Kobenhavn" here really is
    # what "Kobenhavn" normalizes to, not a typo.
    "sport lisboa e benfica": "Benfica", "sl benfica": "Benfica",
    "sporting clube de portugal": "Sp Lisbon", "sporting cp": "Sp Lisbon",
    "royale union saint-gilloise": "St. Gilloise", "union sg": "St. Gilloise",
    "fc kbenhavn": "FC Copenhagen", "kbenhavn": "FC Copenhagen",
    # Brazil Serie A. DANGER: Brazil has three distinct "Atletico" clubs in
    # the training data — Mineiro (Atletico-MG), Paranaense (Athletico-PR)
    # and Goianiense (Atletico GO). They are different clubs; only ever map
    # the full disambiguated name, never a bare "atletico".
    "botafogo fr": "Botafogo RJ", "botafogo": "Botafogo RJ",
    "ca mineiro": "Atletico-MG", "mineiro": "Atletico-MG",
    "ca paranaense": "Athletico-PR", "paranaense": "Athletico-PR",
    "cr flamengo": "Flamengo RJ", "flamengo": "Flamengo RJ",
    "cr vasco da gama": "Vasco", "vasco da gama": "Vasco",
    "chapecoense af": "Chapecoense-SC", "chapecoense": "Chapecoense-SC",
    "clube do remo": "Remo",
    "coritiba fbc": "Coritiba",
    "cruzeiro ec": "Cruzeiro",
    "ec bahia": "Bahia",
    "ec vitoria": "Vitoria", "vitoria": "Vitoria",
    "fluminense fc": "Fluminense",
    "gremio fbpa": "Gremio", "gremio": "Gremio",
    "mirassol fc": "Mirassol",
    "rb bragantino": "Bragantino",
    "sc corinthians paulista": "Corinthians",
    "sc internacional": "Internacional",
    "se palmeiras": "Palmeiras",
    "santos fc": "Santos",
    "sao paulo fc": "Sao Paulo", "sao paulo": "Sao Paulo",
}


# Pretty display names for our abbreviated training-data keys, so the SAME club
# reads the same on every page (Predict/Simulate/Fixtures). Verified by hand;
# anything not listed falls back to its key (already clean, e.g. "Liverpool",
# "Arsenal", "Bayern Munich"), so this only needs the abbreviated/odd forms.
# The key stays the lookup id everywhere; only the label changes.
PRETTY_NAME = {
    # England
    "Man City": "Manchester City", "Man United": "Manchester United",
    "Nott'm Forest": "Nottingham Forest", "Wolves": "Wolverhampton",
    "West Brom": "West Bromwich Albion", "Sheffield Weds": "Sheffield Wednesday",
    "QPR": "Queens Park Rangers", "Bristol Rvs": "Bristol Rovers",
    # Spain
    "Ath Madrid": "Atlético Madrid", "Ath Bilbao": "Athletic Bilbao",
    "Espanol": "Espanyol", "Vallecano": "Rayo Vallecano",
    "La Coruna": "Deportivo La Coruña", "Sociedad": "Real Sociedad",
    "Betis": "Real Betis", "Sevilla": "Sevilla", "Celta": "Celta Vigo",
    # Germany
    "M'gladbach": "Borussia Mönchengladbach", "Ein Frankfurt": "Eintracht Frankfurt",
    "FC Koln": "FC Köln", "Werder Bremen": "Werder Bremen", "Nurnberg": "Nürnberg",
    "Fortuna Dusseldorf": "Fortuna Düsseldorf",
    # France
    "Paris SG": "Paris Saint-Germain", "St Etienne": "Saint-Étienne",
    # Netherlands / Portugal / Belgium
    "For Sittard": "Fortuna Sittard", "Sp Lisbon": "Sporting CP",
    "St Truiden": "Sint-Truiden", "St. Gilloise": "Union Saint-Gilloise",
    # Brazil
    "Botafogo RJ": "Botafogo", "Atletico-MG": "Atlético Mineiro",
    "Athletico-PR": "Athletico Paranaense", "Flamengo RJ": "Flamengo",
    "Vasco": "Vasco da Gama", "Gremio": "Grêmio", "Sao Paulo": "São Paulo",
    "Chapecoense-SC": "Chapecoense",
}


def team_display_name(key: str) -> str:
    """Canonical display label for a team_stats key — the same string on every
    page. Falls back to the key (already the common short name)."""
    return PRETTY_NAME.get(key, key or "")


def resolve_team_name(name: str, team_stats: dict) -> "str | None":
    """Best-effort resolution of an external (e.g. live-API) team name to a
    team_stats.json key. Returns None if genuinely unresolved — callers must
    treat that as "unknown team", not guess further."""
    if not name:
        return None
    if name in team_stats:
        return name
    normalized = strip_accents(name).strip().lower()
    canonical = TEAM_NAME_ALIASES.get(normalized)
    if canonical and canonical in team_stats:
        return canonical
    return None
