"""Reconciles team names between football-data.org (the live API, used for
the Fixtures page — official long names like "Manchester United FC") and the
training data's naming convention (football-data.co.uk/footballcsv, short
common names like "Man United").

Every entry below was verified by hand against team_stats.json — NOT
generated by fuzzy/similarity matching. That was tried first and rejected:
character-similarity matching produced dangerous false positives like
"Rayo Vallecano de Madrid" -> "Real Madrid" and "RCD Espanyol de Barcelona"
-> "Barcelona" (fierce rivals, not the same club) — a club's full name often
embeds the city name, which collides with another real club's short name.
Wrong-team predictions that *look* plausible are worse than an honest
"unknown team" fallback, so resolution here is exact-or-nothing.

Keys are accent-stripped, lowercased source names (either football-data.org's
`name` or `shortName` field) -> the canonical team_stats.json key.
"""

import unicodedata


def strip_accents(text: str) -> str:
    if not text:
        return ""
    return unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")


# Verified against team_stats.json for PL, PD, BL1, SA, FL1, DED, PPL, ELC —
# the leagues actually offered on the Fixtures page. Extend as new mismatches
# turn up; never add an entry without checking it against team_stats.json.
TEAM_NAME_ALIASES = {
    # Bundesliga
    "fc bayern munchen": "Bayern Munich", "bayern": "Bayern Munich",
    "sc paderborn 07": "Paderborn", "sc paderborn": "Paderborn",
    "eintracht frankfurt": "Ein Frankfurt", "frankfurt": "Ein Frankfurt",
    "1. fc koln": "FC Koln",
    "hamburger sv": "Hamburg", "hsv": "Hamburg",
    "sv werder bremen": "Werder Bremen", "bremen": "Werder Bremen",
    "fc schalke 04": "Schalke 04", "schalke": "Schalke 04",
    # Eredivisie
    "psv": "PSV Eindhoven",
    "fortuna sittard": "For Sittard", "sittard": "For Sittard",
    "az": "AZ Alkmaar",
    # Ligue 1
    "racing club de lens": "Lens", "rc lens": "Lens",
    "paris saint-germain fc": "Paris SG", "psg": "Paris SG",
    "stade rennais fc 1901": "Rennes", "stade rennais": "Rennes",
    "angers sco": "Angers",
    "olympique lyonnais": "Lyon", "olympique lyon": "Lyon",
    # La Liga
    "deportivo alaves": "Alaves", "alaves": "Alaves",
    "sevilla fc": "Sevilla",
    "rayo vallecano de madrid": "Vallecano", "rayo vallecano": "Vallecano",
    "rcd espanyol de barcelona": "Espanol", "espanyol": "Espanol",
    "rc deportivo la coruna": "La Coruna", "deportivo": "La Coruna",
    "club atletico de madrid": "Ath Madrid", "atleti": "Ath Madrid",
    "malaga cf": "Malaga", "malaga": "Malaga",
    "real betis balompie": "Betis", "real betis": "Betis",
    "real sociedad de futbol": "Sociedad", "real sociedad": "Sociedad",
    "athletic club": "Ath Bilbao", "athletic": "Ath Bilbao",
    "fc barcelona": "Barcelona", "barca": "Barcelona",
    # Premier League — most already resolve via shortName exact match (e.g.
    # "Manchester United FC" -> shortName "Man United" hits team_stats
    # directly), these cover the long `name` form for direct/bookmarked URLs.
    "manchester united fc": "Man United", "manchester united": "Man United",
    "manchester city fc": "Man City", "manchester city": "Man City",
    "tottenham hotspur fc": "Tottenham", "tottenham hotspur": "Tottenham",
    "newcastle united fc": "Newcastle", "newcastle united": "Newcastle",
    "west ham united fc": "West Ham", "west ham united": "West Ham",
    "wolverhampton wanderers fc": "Wolves", "wolverhampton wanderers": "Wolves",
    "coventry city fc": "Coventry", "coventry city": "Coventry",
    "hull city afc": "Hull", "hull city": "Hull",
    "ipswich town fc": "Ipswich", "ipswich town": "Ipswich",
    "nottingham forest fc": "Nott'm Forest", "nottingham": "Nott'm Forest",
    "leeds united fc": "Leeds", "leeds united": "Leeds",
    "brighton & hove albion fc": "Brighton", "brighton hove": "Brighton",
    # Serie A
    "como 1907": "Como",
    "venezia fc": "Venezia",
}


def resolve_team_name(name: str, team_stats: dict) -> "str | None":
    """Best-effort resolution of an external (e.g. live-API) team name to a
    team_stats.json key. Returns None if genuinely unresolved — callers must
    treat that as "unknown team", not guess further."""
    if not name:
        return None
    if name in team_stats:
        return name
    normalized = strip_accents(name).strip().lower()
    canonical = TEAM_NAME_ALIASES.get(normalized)
    if canonical and canonical in team_stats:
        return canonical
    return None
